//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFrameWorkDatabaseFirst.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CodeFirstExampleEntities : DbContext
    {
        public CodeFirstExampleEntities()
            : base("name=CodeFirstExampleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Products> Products { get; set; }
    
        public virtual ObjectResult<sp_getProduct_Result> sp_getProduct()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getProduct_Result>("sp_getProduct");
        }
    }
}
